# 복습
jupyter notebook 사용법
- cell : 코드를 실행하는 하나의 작은 상자
- [shift] + [enter] : 셀 실행
- [alt] + [enter] : 하단에 셀을 추가하며 실행
- [esc] + [M] : 마크다운 모드로 변경
- [esc] + [Y] : 코드 모드
- [ctr] + [/] : 주석모드

In [1]:
# 300 + 100

In [2]:
300
# 200
100

100

# 파이썬 기초 문법
- 변수 : 데이터를 담는 상자

In [3]:
data1 = 100
data2 = 200

In [4]:
data1 * data2

20000

# 자료구조
- 리스트 : [대괄호]
- 튜플 : (소괄호)
- 세트 : {중괄호}
- 딕셔너리 : {'key1': 'value1','key2': 'value2',...}

In [5]:
dict1 = {'이름':'홍길동','나이':25}
dict1

{'이름': '홍길동', '나이': 25}

In [6]:
dict1['이름']

'홍길동'

In [7]:
input1 = input('입력하시오')
input1

입력하시오 21


'21'

In [8]:
type(input1)

str

In [9]:
input2 = int(input('숫자를 입력하시오'))
type(input2)

숫자를 입력하시오 12


int

# 조건문
- if / else / elif
- in/ not in
- pass

In [10]:
data1 = int(input())
if data1 > 30:
    print('30 보다 큽니다')
else : 
    print('30 보다 작습니다.')

 12


30 보다 작습니다.


In [11]:
data1 = 0
while data1 < 10 :
    data1 = data1 + 1
    print(data1)

1
2
3
4
5
6
7
8
9
10


In [12]:
for i in ['a','b','c'] :
    print(i)

a
b
c


In [13]:
# 리스트 컴프리헨션 미션 사용할 때 사용
[x for x in range(6)]

#range(n) : n-1까지 숫자를 출력

[0, 1, 2, 3, 4, 5]

In [14]:
for i in range(6):
    print(i,end=" ")

0 1 2 3 4 5 

In [15]:
def func1(x):
    return x+200

func1(2)

202

In [16]:
def func2(x1,x2,cond1 = True):
    if cond1 == True:
        return x1 + x2
    else :
        return x1 - x2

In [17]:
func2(100,200)

300

In [18]:
func2(100,200,False)

-100

# 예외처리
- try : 실행하려는 코드
- except: 에러가 난 경우에 실행할 코드
- finally : 에러의 유무에 상관 없이 최종적으로 실행할 코드

In [19]:
try : 
    data1=[]
    for i in range(1,6):
        data1.remove(1)
        data1.append(i)
    print('no error')
except :
    print('error')
finally : 
    print(data1)
    print('done')

error
[]
done


미션풀이

### 반복문 1~2번 문제

In [20]:
input1 = input('숫자를 입력하시오')
type(input1)

숫자를 입력하시오 21


str

In [21]:
input2 = int(input('숫자를 입력하시오'))
type(input2)

숫자를 입력하시오 12


int

In [22]:
input_number = input('숫자를 입력하시오. 띄어쓰기로 구분')
input_list = input_number.split(' ')
input_list

숫자를 입력하시오. 띄어쓰기로 구분 231 1 2


['231', '1', '2']

In [23]:
[int(x) for x in input_list]

[231, 1, 2]

In [24]:
input_number = input('숫자를 입력하시오. 띄어쓰기로 구분')
list1 = input_number.split(' ')
list2 = [int(x) for x in list1]

result1 = 0
for i in list2:
    result1 = result1 + i

print(result1)

숫자를 입력하시오. 띄어쓰기로 구분 3 12 4


19


In [25]:
# 2번
list1 = [x for x in range(1,6)]
sum(list1)/ len(list1)

3.0

In [27]:
# 숙련자
input_number = input('숫자를 입력하시오. 띄어쓰기로 구분')
list1 = input_number.split(' ')
list2 = [int(x) for x in list1]

print(sum(list2)/len(list2))

숫자를 입력하시오. 띄어쓰기로 구분 1 2 3 4


2.5


### 미션 반복문 3번 문제

In [29]:
input_data = input('이름과 성적 5개를 입력하시오 띄어쓰기로 구분')
input_data

이름과 성적 5개를 입력하시오 띄어쓰기로 구분 홍길동 100 100 100 100 100


'홍길동 100 100 100 100 100'

In [30]:
list1 = input_data.split(' ')
list1

['홍길동', '100', '100', '100', '100', '100']

In [31]:
name = list1[0]
scores = list1[1:] # 1번 인덱스부터 끝까지 (2번째 순서)

In [32]:
scores_2=[int(x) for x in scores]
scores_2

[100, 100, 100, 100, 100]

In [33]:
input_data = input('이름과 성적 5개를 입력하시오: ')
list1 = input_data.split(' ')
name = list1[0]
scores = [int(x) for x in list1[1:]]
avg = sum(scores) / len(scores)

if avg >= 90:
    print(f'{name} 학생의 성적은 {avg}이고, A 입니다.')
elif avg >= 80:
    print(f'{name} 학생의 성적은 {avg}이고, B 입니다.')
elif avg >= 70:
    print(f'{name} 학생의 성적은 {avg}이고, C 입니다.')
else:
    print(f'{name} 학생의 성적은 {avg}이고, F 입니다.')


이름과 성적 5개를 입력하시오:  홍길동 1 2 3 4 5


홍길동 학생의 성적은 3.0이고, F 입니다.


In [34]:
input_year = int(input('연도를 입력하시오'))
if (input_year % 4 ==0) & (input_year % 100 !=0) | (input_year % 400 ==0):
    print(f'{input_year}는 윤년입니다')
else:
    print(f'{input_year}는 평년입니다')

연도를 입력하시오 2024


2024는 윤년입니다


In [35]:
input_year = int(input('연도를 입력하시오'))
dict1 = {True :'윤년입니다', False : '평년입니다'}
cond1 = ((input_year % 4 ==0) & (input_year % 100 !=0) | (input_year % 400 ==0))
dict1[cond1]

연도를 입력하시오 2024


'윤년입니다'

# 데이터 분석 라이브러리

- numpy : numeric + python : 연속형,수치형 자료 과학/수학/통계/ 연산을 수행하는 라이브러리. 딥러닝/ 비정형 데이터를 다루는데 많이 쓰임
- pandas : panel1 + dataset : 정형데이터 (excel, csv , rdb , sql , ...) 를 다루는 라이브러리
- matplot : matlab + plot : 연속형 데이터 그래프 시각화 라이브러리
- seaborn : 정형데이터 통계분석 시각화 라이브러리
- plotly : 정형데이터 동적 시각화 라이브러리
- missingno : 결측치 패턴 , 수 , 시각화 라이브러리
- scipy : science + python 응용통계 (가설검정/회귀분석/시계열/...) 라이브러리
- scikit-learn :science + python + toolkit + learning : 정형 데이터를 이용한 데이터 마이닝 , 머신러닝 라이브러리
- tensorflow : 비정형데이터 (이미지, 영상 , 자연어) 라이브러리
- keras : tensorlow 기반 딥러닝 학습 라이브러리
- pytorch : 비정형 데이터 관련 라이브러리
- konlpy : Korean Natural Language Process python : 한국어 자연어 처리 라이브러리

# Numpy
- numeric + python
- 정형데이터의 기본이 되는 형태
- 초기 데이터 분석에 많이 쓰였지만 , 지금은 비정형 데이터에 주로 쓰인다

In [36]:
import numpy as np


In [37]:
list1 = [1,3,5]
list1.mean()
#에러

AttributeError: 'list' object has no attribute 'mean'

In [38]:
data1 = np.array([1,2,3])
type(data1) #nd array : n-dimensional

numpy.ndarray

In [39]:
data1.ndim #배열의 축 수 

1

In [40]:
# 0 scalar
# 1 : vector
# 2 : matricx
# 3 : tensor
np.array([[1,2],[2,3]]).ndim

2

In [41]:
data1.mean()

2.0

In [42]:
data1.max() # 최대값

3

In [43]:
[x for x in range(0,10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(1,20,3)

# 1부터 20까지 3의 간격으로 벡터 생성

array([ 1,  4,  7, 10, 13, 16, 19])

In [46]:
np.linspace(1,10,7)
# 1에서 10까지를 7개로 쪼개서 반환

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

## 미션 풀이

### 1. 하나의 리스트를 입력 받았을 때 , 중복값을 제거하고 출력하는 함수를 만드시오.

In [47]:
def func1(list1):
    return list(set(list1))
func1([1,1,1,2,3,3,4,5])

[1, 2, 3, 4, 5]

In [1]:
# 2. 입력받은 튜플을 오름차순으로 정렬하는 함수를 만드시오

def func2(tuple1) :
    return sorted(tuple1)

func2((1,3,-1,2,4))

[-1, 1, 2, 3, 4]

In [49]:
# 3. 1부터 100까지의 숫자 중 6개의 숫자를 중복 없이 임의로 생성하는 함수를 만드시오.
import random
def func3():
    result1 =[]
    while len(result1) < 6:
        num = random.randint(1,100)
        if num in result1:
            continue
        else : 
            result1.append(num)
    return result1

In [50]:
func3()
        

[30, 19, 39, 11, 53, 37]

In [51]:
random.sample(range(101),6)

[73, 69, 19, 95, 25, 52]

In [52]:
# 4. 숫자를 입력받아 짝/홀수를 판별하는 프로그램을 if문 없이 만드시오.
def func4():
    num = int(input('숫자를 입력하시오'))
    cond1 = num % 2 ==0
    # dict1 = {True : '짝수입니다.',False : '홀수입니다.'}
    dict1 = {True : f'{num}는 짝수입니다.',False : '홀수입니다.'}
    return dict1[cond1]

In [53]:
func4()

숫자를 입력하시오 4


'4는 짝수입니다.'

In [54]:
# 5. 1부터 30의 숫자 중 홀수만 갖는 리스트를 만드시오
[x for x in range(0,31) if x % 2 !=0]

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

In [55]:
import numpy as np
np.arange(1,31,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [56]:
list1 = [x for x in range(0,31)]
result1 = []
for i in list1:
    if i % 2 !=0:
        result1.append(i)

result1

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

In [57]:
# 6. 1부터 30의 숫자 중 3의 배수이지만 4의 배수는 아닌 숫자를 출력하시오
[x for x in range(1,31) if (x%3 ==0) & (x%4 !=0)]

[3, 6, 9, 15, 18, 21, 27, 30]

## 7. 아래 두 리스트의 중복값을 제거한 후 오름차순으로 하나의 리스트로 출력하는 함수를 만드시오
- list1 = [100,200,500,600,700]
- list2 = [500,600,700,800,900]

In [58]:
list1 = [100,200,500,600,700]
list2 = [500,600,700,800,900]
list3 = list1 + list2
list3

[100, 200, 500, 600, 700, 500, 600, 700, 800, 900]

In [59]:
def func7():
    list1 = [100,200,500,600,700]
    list2 = [500,600,700,800,900]
    list3 = list1 + list2
    return sorted(set(list3))

In [60]:
func7()

[100, 200, 500, 600, 700, 800, 900]

## 8. 1~50 사이의 숫자를 랜덤으로 생성한 후, 숫자를 맞출 때까지 값을 입력해서 맞추는 프로그램을 생성. (업다운 게임)

- 숙련자 : 시도한 횟수도 표시

In [61]:
target = random.randint(0,5)
target

4

In [62]:
guess = int(input('숫자를 입력하시오'))
guess

숫자를 입력하시오 2


2

In [63]:
if target == guess:
    print('성공입니다')
elif target > guess:
    print('업')
elif target < guess :
    print('다운')

업


In [64]:
target = random.randint(0,5)

while True:
    guess = int(input('숫자를 입력하시오'))
    if target == guess:
        print('성공입니다')
        break
    elif target > guess:
        print('업')
    elif target < guess :
        print('다운')

숫자를 입력하시오 2


다운


숫자를 입력하시오 1


성공입니다


In [ ]:
def func8():
    target = random.randint(0,5)
    count = 1
    
    while True:
        guess = int(input('숫자를 입력하시오'))
        if target == guess:
            return f'성공입니다! 시도한 횟수는 {count} 입니다'
            break
        elif target > guess :
            count = count + 1
            print('업')
        elif target < guess :
            count = count + 1
            print('다운')

In [3]:
# 행렬

# 행 : 가로
# 열 : 세로

m1 = [[0,0,1],[0,1,0],[1,0,0]]
m1

[[0, 0, 1], [0, 1, 0], [1, 0, 0]]

In [4]:
import numpy as np
data1 = np.array(m1)
data1

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [5]:
type(data1)

numpy.ndarray

In [6]:
data1.ndim
#2 : matrix

2

In [7]:
# 행렬의 연산

data4 = np.array([[1,2],[3,4],[5,6]]) # 3x2
data5 = np.array([[1,2],[3,4],[5,6]]) # 3x2

data4 + data5

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [8]:
data4 - data5

array([[0, 0],
       [0, 0],
       [0, 0]])

In [15]:
# 행렬의 곱

#앞의 행
# 뒤의 열이 같아야 곱해진다
data6 = np.array([[1,2],[3,4],[5,6]]) # 3x2
data7 = np.array([[1,2,3],[4,5,6]]) # 2x3

data6 @ data7

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [12]:
data5 = np.array([['a','b','c'],['d','e','f'],['g','h','i']])
data5

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [13]:
data5[0]

array(['a', 'b', 'c'], dtype='<U1')

In [14]:
data5[0,0] = 'z'
data5

array([['z', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [17]:
data5 [1] = ['x','y','z']
data5

array([['z', 'b', 'c'],
       ['x', 'y', 'z'],
       ['g', 'h', 'i']], dtype='<U1')

In [18]:
data6 = np.array(data5,dtype = '<U2')
data6

array([['z', 'b', 'c'],
       ['x', 'y', 'z'],
       ['g', 'h', 'i']], dtype='<U2')

In [19]:
data6[0,0] = 'a1'
data6

array([['a1', 'b', 'c'],
       ['x', 'y', 'z'],
       ['g', 'h', 'i']], dtype='<U2')

In [20]:
# vertical stack
np.vstack([data7,[1,2,3]]) # 열 추가 , 수직

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [24]:
# horizontal stack
np.hstack([data7, [[1],[2]]]) # 행 추가 , 수평

array([[1, 2, 3, 1],
       [4, 5, 6, 2]])

In [25]:
# 재구조화
data8 = np.array([1,25,25,1])
data8

array([ 1, 25, 25,  1])

In [26]:
data8.reshape(2,2)

array([[ 1, 25],
       [25,  1]])

In [27]:
data9 =np.linspace(1,25,9) # 1부터 25까지의 9개의 일정한 간격으로 요소를 만듬
data9

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

In [28]:
data9.reshape(3,3)

array([[ 1.,  4.,  7.],
       [10., 13., 16.],
       [19., 22., 25.]])

In [29]:
data11 = np.random.rand(2,3) 
data11

array([[0.84062165, 0.12194597, 0.70871862],
       [0.2292811 , 0.63225486, 0.18145512]])

In [30]:
# 매트릭스 값 확인
data11

array([[0.84062165, 0.12194597, 0.70871862],
       [0.2292811 , 0.63225486, 0.18145512]])

In [32]:
data11.sum()

2.7142773228706956

In [33]:
data11.mean()

0.4523795538117826

In [35]:
data11.sum(axis = 0) # axis = 0 은 열단위

array([1.06990276, 0.75420083, 0.89017374])

In [37]:
data11.sum(axis = 1) # axis = 1 은 행 단위

array([1.67128625, 1.04299108])

In [38]:
data11.mean(axis = 0) # 열단위

array([0.53495138, 0.37710041, 0.44508687])

In [39]:
data11.mean(axis =1) # 행 단위

array([0.55709542, 0.34766369])

In [40]:
data11.max()

0.8406216534592228

In [41]:
data11.max(axis =1)

array([0.84062165, 0.63225486])

In [42]:
data11.min() # 최소값

0.12194596950722836

# pandas
- panel + dataset
- series : numpy array를 기반으로 만들어진 정형 데이터 분석 index -- value 형식의 자료구조

In [43]:
import pandas as pd


In [46]:
s1 = pd.Series([1,2,3])
s1

0    1
1    2
2    3
dtype: int64

In [49]:
s2 = pd.Series(['a','b','c',4])
s2

# 시리즈는 하나의 데이터 타입만 올 수 있다

0    a
1    b
2    c
3    4
dtype: object

In [50]:
s2.index

RangeIndex(start=0, stop=4, step=1)

In [52]:
s2.values # 바로 불러오는 함수 values

array(['a', 'b', 'c', 4], dtype=object)

In [53]:
type(s2) # 데이터 타입을 자주 확인 해야 안에 도메인을 가져오기 좋다

pandas.core.series.Series

In [55]:
type(s1.values) #numpy 라이브러리를 기반으로 만들어짐

numpy.ndarray

In [56]:
# series indexing
s2

0    a
1    b
2    c
3    4
dtype: object

In [57]:
s2[0]

'a'

In [59]:
# series slicing
s2[0:2]

0    a
1    b
dtype: object

In [60]:
# 값 대체
s1[0] = 99
s1

0    99
1     2
2     3
dtype: int64

In [63]:
# 값 삭제
s1.drop(0) # 원본 변수에 영향을 미치는 삭제 함수가 아니다

1    2
2    3
dtype: int64

In [64]:
s1

0    99
1     2
2     3
dtype: int64

In [65]:
s3 = s1.drop(0)
s3

1    2
2    3
dtype: int64

In [80]:
s1.drop(0, inplace= True) # inplace 옵션 사용 시 , 원본 변수에 수정을 가함
s1

인덱스 0는 Series에 존재하지 않습니다.


In [71]:
# index 지정
s4 = pd.Series ([1,2,3,4,5,] , index=['a','b','c','d','e'])
s4

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [72]:
# 인덱싱
s4['a']

1

In [73]:
# 딕셔너리로 series 구성
s5 = pd.Series({'name':'둘리','age':5,'area':'서울'})
s5

name    둘리
age      5
area    서울
dtype: object

In [81]:
# 인덱스 이름 변경
s6= s5.rename(index={'name':'이름'})
s6

이름       둘리
age       5
area     서울
친구      희동이
dtype: object

In [ ]:
s5.rename(index={'name','이름'} , inplace = True)

In [79]:
#새로운 값 추가 
s5['친구'] = '희동이'
s5

name     둘리
age       5
area     서울
친구      희동이
dtype: object

In [83]:
df = pd.DataFrame([100,200,300,400])
df

0
0  100
1  200
2  300
3  400

In [84]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [85]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [86]:
df.values

array([[100],
       [200],
       [300],
       [400]], dtype=int64)

In [89]:
# column을 지정하여 데이터 프레임을 구성
df1 = pd.DataFrame(data = [[100,200,300,400,500],
                          [40,200,22,22,23]],
                  columns = ['A','B','C','D','E'])
df1

A    B    C    D    E
0  100  200  300  400  500
1   40  200   22   22   23

In [90]:
df1.index

RangeIndex(start=0, stop=2, step=1)

In [91]:
df1['A']

0    100
1     40
Name: A, dtype: int64

In [93]:
type(df1['A'])

pandas.core.series.Series

In [94]:
df1['A'].values

array([100,  40], dtype=int64)

In [95]:
df1[['A','B']]

A    B
0  100  200
1   40  200

In [96]:
df1[['A']] #이중리스트로 하나의 컬럼을 호출하는 경우
# 데이터 프레임 형태로

A
0  100
1   40

In [4]:
import pandas as pd
# column을 지정하여 데이터 프레임을 구성
df2 = pd.DataFrame(data = [['오덕이',100,80,70],
                          ['이기영',70,60,70],
                          ['이기철',60,70,80]],
                  columns = ['이름','국어','수학','체육'])
df2

이름   국어  수학  체육
0  오덕이  100  80  70
1  이기영   70  60  70
2  이기철   60  70  80

In [99]:
df2.index

RangeIndex(start=0, stop=3, step=1)

In [100]:
df2.values

array([['오덕이', 100, 80, 70],
       ['이기영', 70, 60, 70],
       ['이기철', 60, 70, 80]], dtype=object)

In [101]:
df2.columns

Index(['이름', '국어', '수학', '체육'], dtype='object')

In [102]:
df2['이름']

0    오덕이
1    이기영
2    이기철
Name: 이름, dtype: object

In [103]:
df2.iloc[0] # index location , 
# df2.iloc[행 인덱스 , 열 인덱스] 컴퓨터가 읽기 좋은 방법, 
#loc는 칼럼명을 직접 적거나 특정 조건식을 써줌으로써 사람이 읽기 쉽다

이름    오덕이
국어    100
수학     80
체육     70
Name: 0, dtype: object

In [104]:
df2

이름   국어  수학  체육
0  오덕이  100  80  70
1  이기영   70  60  70
2  이기철   60  70  80

In [8]:
df2.iloc[0]

이름    오덕이
국어    100
수학     80
체육     70
Name: 0, dtype: object

In [107]:
df2.iloc[0].values


array(['오덕이', 100, 80, 70], dtype=object)

In [110]:
df2.set_index('이름',inplace = True) #set_index 열을 인덱스로 설정

In [111]:
df2

국어  수학  체육
이름              
오덕이  100  80  70
이기영   70  60  70
이기철   60  70  80

In [112]:
df2.iloc[0] #iloc : 숫자만 입력 가능

국어    100
수학     80
체육     70
Name: 오덕이, dtype: int64

In [114]:
df2.loc['오덕이'] #loc : 문자도 입력 가능

국어    100
수학     80
체육     70
Name: 오덕이, dtype: int64

In [118]:
# 딕셔너리를 통해 DataFrame 생성
# 키값이 컬럼명으로 들어가고
# value 값은 컬럼의 값들로 채워진다.


df3 = pd.DataFrame( data = {'장르':['팝','록'],
                           '아티스트':['마이클잭슨','비틀즈'],
                           '곡':['rock with you','julia']})

In [119]:
df3

장르   아티스트              곡
0  팝  마이클잭슨  rock with you
1  록    비틀즈          julia

### DDA
- Descriptive Data Analysis
- 기술적 데이터 분석
- 비즈니스 목표에 부합하는 변수 확인
- 목표변수 Y (target,label,output, ...)
- 설명변수 X(feature,input, . . .)
- 기술통계량 확인(평군 / 중위수 / 분산/ . . .)

# 01_Data.csv
- 사무용품을 렌탈해주는 업체의 고객 데이터


In [10]:
df1 = pd.read_csv('01_Data.csv')

In [11]:
pd.read_csv('01_Data.csv')

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
0          1   66758234         렌탈          일반계약    영업방판  2022-05-05    60   
1          2   66755948         렌탈          교체계약    영업방판  2023-02-19    60   
2          3   66756657         렌탈          일반계약  홈쇼핑/방송  2022-02-27    60   
3          4   66423450        멤버십        멤버십3유형     재계약  2022-05-12    12   
4          5   66423204        멤버십        멤버십3유형     재계약  2022-05-09    12   
...      ...        ...        ...           ...     ...         ...   ...   
51296  51298   66579515         렌탈        프로모션계약   대형마트A  2022-02-28    60   
51297  51299   66799558         렌탈          일반계약   대형마트A  2022-03-31    60   
51298  51300   66799197         렌탈        프로모션계약    영업방판  2022-03-31    39   
51299  51301   66792778         렌탈          일반계약  홈쇼핑/방송  2023-02-05    60   
51300  51302   66799607         렌탈          일반계약  홈쇼핑/방송  2022-04-23    60   

      Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
0              CMS        DES-1         96900            개인  42.0      경기도   
1             카드이체        DES-1        102900            개인  39.0      경기도   
2              CMS        DES-1         96900            개인  48.0      경기도   
3              CMS        DES-1         66900            개인  39.0      경기도   
4              CMS        DES-1         66900            개인  60.0      경기도   
...            ...          ...           ...           ...   ...      ...   
51296          CMS       DES-3A         96900            개인  47.0      경기도   
51297          CMS        DES-1         96900            개인  42.0      경기도   
51298         카드이체          ERA        120900            개인  65.0    서울특별시   
51299         카드이체        DES-1         96900            개인  54.0    서울특별시   
51300          CMS        DES-1         96900            개인  53.0    서울특별시   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank    Bank  
0          경기도  계약확정              0           없음     여자          9.0   새마을금고  
1          경기도  계약확정              0           없음     남자          2.0    현대카드  
2          경기도  계약확정              0           없음     여자          8.0    우리은행  
3          경기도  계약확정              0           없음     남자          5.0  농협회원조합  
4          경기도  기간만료             12           있음     남자          8.0  농협회원조합  
...        ...   ...            ...          ...    ...          ...     ...  
51296      경기도  계약확정              0           없음     남자          NaN    기업은행  
51297      경기도  계약확정              0           없음     여자          8.0   새마을금고  
51298    서울특별시  계약확정              0           없음     여자          1.0    롯데카드  
51299    서울특별시  계약확정              0           없음     여자          2.0    롯데카드  
51300    서울특별시  계약확정              0           없음     여자          8.0    신한은행  

[51301 rows x 20 columns]

In [12]:
df1['Customer_Type'].value_counts()

Customer_Type
 개인     46263
 사업자     5036
Name: count, dtype: int64

# 데이터의 구조와 타입을 확인
- index -- column -- value를 확인
- index :  데이터의 개수를 확인
  - 데이터의 개수에 따라 분석 방법이 달라짐
- column : 데이터의 열 / 데이터의 항목
  - 각 항목별(열) 데이터 타입을 확인
    - 연속형 : int/ float
    - 범주형 :: object
    - 순서형 : 날짜 / 시간데이터 (datetime)
- value : 값
  - 데이터의 형식 (format) 확인
  - 원시자료설명서 / DB 설계서 / 변수정의서
  - 결측값 (missin value) : 데이터 수집 중 오류나 누락으로 인해 비어있는 값 : None / NaN (Not a Number) / Na( Not Available) / Null / inf /. . .

In [123]:
# 인덱스 확인
df1.index

RangeIndex(start=0, stop=51301, step=1)

In [125]:
# 행렬 확인
df1.shape  # (531301-> 행렬)

(51301, 20)

In [126]:
df1.columns #항목확인

Index(['Index', 'Member_ID', 'Sales_Type', 'Contract_Type', 'Channel',
       'Datetime', 'Term', 'Payment_Type', 'Product_Type', 'Amount_Month',
       'Customer_Type', 'Age', 'Address1', 'Address2', 'State',
       'Overdue_count', 'Overdue_Type', 'Gender', 'Credit_Rank', 'Bank'],
      dtype='object')

In [127]:
len(df1) #index 확인 가능

51301

### info를 사용하면 데이터의 구조를 다 볼 수 있다.

In [129]:
df1.info() # info를 사용하면 데이터의 구조를 다 볼 수 있다.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51301 entries, 0 to 51300
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Index          51301 non-null  int64  
 1   Member_ID      51301 non-null  int64  
 2   Sales_Type     51301 non-null  object 
 3   Contract_Type  51301 non-null  object 
 4   Channel        51301 non-null  object 
 5   Datetime       51301 non-null  object 
 6   Term           51301 non-null  int64  
 7   Payment_Type   51301 non-null  object 
 8   Product_Type   51301 non-null  object 
 9   Amount_Month   51301 non-null  int64  
 10  Customer_Type  51299 non-null  object 
 11  Age            44329 non-null  float64
 12  Address1       51299 non-null  object 
 13  Address2       51299 non-null  object 
 14  State          51301 non-null  object 
 15  Overdue_count  51301 non-null  int64  
 16  Overdue_Type   51301 non-null  object 
 17  Gender         51301 non-null  object 
 18  Credit

In [14]:
# 결측치 확인
df1.isnull().sum()  #결측치의 개수를 구해줌 sum까지 하면()

Index               0
Member_ID           0
Sales_Type          0
Contract_Type       0
Channel             0
Datetime            0
Term                0
Payment_Type        0
Product_Type        0
Amount_Month        0
Customer_Type       2
Age              6972
Address1            2
Address2            2
State               0
Overdue_count       0
Overdue_Type        0
Gender              0
Credit_Rank      8781
Bank             2759
dtype: int64

In [132]:
# 데이터 추출(행 단위)

df1.head() #위에 입력된 개수 만큼 확인 , head() : 디폴트로 5 줄만 보여줌

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
0      1   66758234         렌탈          일반계약    영업방판  2022-05-05    60   
1      2   66755948         렌탈          교체계약    영업방판  2023-02-19    60   
2      3   66756657         렌탈          일반계약  홈쇼핑/방송  2022-02-27    60   
3      4   66423450        멤버십        멤버십3유형     재계약  2022-05-12    12   
4      5   66423204        멤버십        멤버십3유형     재계약  2022-05-09    12   

  Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
0          CMS        DES-1         96900            개인  42.0      경기도   
1         카드이체        DES-1        102900            개인  39.0      경기도   
2          CMS        DES-1         96900            개인  48.0      경기도   
3          CMS        DES-1         66900            개인  39.0      경기도   
4          CMS        DES-1         66900            개인  60.0      경기도   

  Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank    Bank  
0      경기도  계약확정              0           없음     여자          9.0   새마을금고  
1      경기도  계약확정              0           없음     남자          2.0    현대카드  
2      경기도  계약확정              0           없음     여자          8.0    우리은행  
3      경기도  계약확정              0           없음     남자          5.0  농협회원조합  
4      경기도  기간만료             12           있음     남자          8.0  농협회원조합

In [133]:
df1.head(8) 

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
0      1   66758234         렌탈          일반계약    영업방판  2022-05-05    60   
1      2   66755948         렌탈          교체계약    영업방판  2023-02-19    60   
2      3   66756657         렌탈          일반계약  홈쇼핑/방송  2022-02-27    60   
3      4   66423450        멤버십        멤버십3유형     재계약  2022-05-12    12   
4      5   66423204        멤버십        멤버십3유형     재계약  2022-05-09    12   
5      6   66165241         렌탈        프로모션계약    영업방판  2022-07-28    60   
6      7   66751017         렌탈         패키지계약  홈쇼핑/방송  2022-01-29    60   
7      8   66751017         렌탈         패키지계약  홈쇼핑/방송  2022-01-16    60   

  Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
0          CMS        DES-1         96900            개인  42.0      경기도   
1         카드이체        DES-1        102900            개인  39.0      경기도   
2          CMS        DES-1         96900            개인  48.0      경기도   
3          CMS        DES-1         66900            개인  39.0      경기도   
4          CMS        DES-1         66900            개인  60.0      경기도   
5          CMS       DES-3A         90900            개인  53.0      경상도   
6         카드이체        DES-1         98400            개인  66.0      경상도   
7         카드이체        DES-2         80400            개인  66.0      경상도   

  Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank    Bank  
0      경기도  계약확정              0           없음     여자          9.0   새마을금고  
1      경기도  계약확정              0           없음     남자          2.0    현대카드  
2      경기도  계약확정              0           없음     여자          8.0    우리은행  
3      경기도  계약확정              0           없음     남자          5.0  농협회원조합  
4      경기도  기간만료             12           있음     남자          8.0  농협회원조합  
5      경상도  계약확정              0           없음     여자          5.0   농협중앙회  
6      경상도  계약확정              0           없음     남자          1.0    롯데카드  
7      경상도  계약확정              0           없음     남자          1.0    롯데카드

In [134]:
# 뒤에서부터 확인
df1.tail()

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
51296  51298   66579515         렌탈        프로모션계약   대형마트A  2022-02-28    60   
51297  51299   66799558         렌탈          일반계약   대형마트A  2022-03-31    60   
51298  51300   66799197         렌탈        프로모션계약    영업방판  2022-03-31    39   
51299  51301   66792778         렌탈          일반계약  홈쇼핑/방송  2023-02-05    60   
51300  51302   66799607         렌탈          일반계약  홈쇼핑/방송  2022-04-23    60   

      Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
51296          CMS       DES-3A         96900            개인  47.0      경기도   
51297          CMS        DES-1         96900            개인  42.0      경기도   
51298         카드이체          ERA        120900            개인  65.0    서울특별시   
51299         카드이체        DES-1         96900            개인  54.0    서울특별시   
51300          CMS        DES-1         96900            개인  53.0    서울특별시   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank   Bank  
51296      경기도  계약확정              0           없음     남자          NaN   기업은행  
51297      경기도  계약확정              0           없음     여자          8.0  새마을금고  
51298    서울특별시  계약확정              0           없음     여자          1.0   롯데카드  
51299    서울특별시  계약확정              0           없음     여자          2.0   롯데카드  
51300    서울특별시  계약확정              0           없음     여자          8.0   신한은행

In [135]:
# iloc 함수 : 중간에 있는 데이터 확인
df1.iloc[50:60]

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
50     51   66758548         렌탈          일반계약    영업방판  2022-03-30    60   
51     52   66758162         렌탈         패키지계약  홈쇼핑/방송  2022-10-02    60   
52     53   66758162         렌탈         패키지계약  홈쇼핑/방송  2022-05-03    60   
53     54   66590304         렌탈        프로모션계약    영업방판  2021-12-31    60   
54     55   66670488         렌탈        프로모션계약    영업방판  2022-04-02    60   
55     56   25856039         렌탈          교체계약    영업방판  2022-04-30    60   
56     57   25869517         렌탈        프로모션계약    영업방판  2022-07-21    60   
57     58   66757967         렌탈        프로모션계약    영업방판  2022-08-20    60   
58     59   66260467         렌탈          교체계약    영업방판  2022-02-15    60   
59     60   66758899         렌탈         패키지계약   전문매장H  2022-07-29    60   

   Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
50          CMS        DES-1         96900            개인  57.0    서울특별시   
51         카드이체        DES-1         98400            개인  50.0    서울특별시   
52         카드이체        DES-2         80400            개인  50.0    서울특별시   
53          CMS        DES-2         90900            개인  43.0    서울특별시   
54          CMS        DES-1         96900            개인  34.0    서울특별시   
55          CMS        DES-1         96900           사업자   NaN      경상도   
56         가상계좌        DES-1         96900           사업자   NaN      경상도   
57         카드이체        DES-1        105900            개인  37.0      경상도   
58          CMS        DES-1         96900            개인  42.0      경상도   
59          CMS        DES-1         81900            개인  67.0      경상도   

   Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank   Bank  
50    서울특별시  계약확정              0           없음     남자          4.0   국민은행  
51    서울특별시  계약확정              0           없음     남자          5.0   국민카드  
52    서울특별시  계약확정              0           없음     남자          5.0   국민카드  
53    서울특별시  계약확정              0           없음     남자          4.0   신한은행  
54    서울특별시  계약확정              0           없음     여자          4.0   우리은행  
55    부산광역시  계약확정              0           없음     여자          NaN  농협중앙회  
56    부산광역시  계약확정              0           없음     여자          NaN    NaN  
57      경상도  계약확정              0           없음     여자          5.0   롯데카드  
58      경상도  계약확정              0           없음     여자          1.0   우리은행  
59      경상도  계약확정              0           없음     남자          2.0   대구은행

In [137]:
# 엑셀로 저장
df1.iloc[50:60].to_excel('result1.xlsx')

In [138]:
df1.iloc[50:61].to_csv('result1.csv')

In [139]:
# 열 단위 추출
df1['Amount_Month']

0         96900
1        102900
2         96900
3         66900
4         66900
          ...  
51296     96900
51297     96900
51298    120900
51299     96900
51300     96900
Name: Amount_Month, Length: 51301, dtype: int64

In [140]:
# 이중리스트 사용 시 데이터 프레임 형태로 출력
df1[['Amount_Month']]

Amount_Month
0             96900
1            102900
2             96900
3             66900
4             66900
...             ...
51296         96900
51297         96900
51298        120900
51299         96900
51300         96900

[51301 rows x 1 columns]

In [141]:
# 여러 컬럼을 출력하는 경우에도 이중 리스트를 사용
df1[['Age','Amount_Month']]

Age  Amount_Month
0      42.0         96900
1      39.0        102900
2      48.0         96900
3      39.0         66900
4      60.0         66900
...     ...           ...
51296  47.0         96900
51297  42.0         96900
51298  65.0        120900
51299  54.0         96900
51300  53.0         96900

[51301 rows x 2 columns]

In [143]:
# 열단위 추출 후 csv 파일로 저장
df1[['Age','Amount_Month']].head(100).to_csv('age100.csv')

# 데이터 정렬
- .sort_values(by =)
- (,asending = False)

In [144]:
# 디폴트는 오름차순으로 보여준다
df1.sort_values(by = 'Amount_Month')

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
35768  35770   66784964        멤버십        멤버십2유형   전문매장H  2022-02-06    36   
43022  43024   66792946        멤버십        멤버십2유형   전문매장H  2023-06-30    36   
49993  49995   66796388        멤버십        멤버십2유형   전문매장H  2023-03-25    36   
33803  33805   66783630        멤버십        멤버십2유형   전문매장H  2023-07-28    36   
45246  45248   66793779        멤버십        멤버십2유형   전문매장H  2022-07-15    36   
...      ...        ...        ...           ...     ...         ...   ...   
5399    5400   25742182         렌탈        프로모션계약    영업방판  2022-05-17    39   
49896  49898   25731710         렌탈        프로모션계약    영업방판  2022-09-29    39   
49897  49899   25731710         렌탈        프로모션계약    영업방판  2022-12-05    39   
28147  28149   25704137         렌탈        프로모션계약    전단홍보  2022-07-24    39   
38497  38499   25734005         렌탈        프로모션계약    영업방판  2022-06-04    39   

      Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
35768          무통장        DES-1         54603            개인   NaN      경기도   
43022          무통장        DES-1         54603            개인   NaN      전라도   
49993          무통장        DES-1         54603            개인   NaN    서울특별시   
33803          무통장        DES-1         54603            개인   NaN      경기도   
45246          무통장        DES-1         54603            개인   NaN    서울특별시   
...            ...          ...           ...           ...   ...      ...   
5399           CMS          MMC        215700           사업자   NaN      경기도   
49896         가상계좌          MMC        215700           사업자   NaN      경기도   
49897         가상계좌          MMC        215700           사업자   NaN      경기도   
28147          CMS          MMC        215700           사업자   NaN      경상도   
38497          CMS          MMC        215700           사업자  58.0      전라도   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank   Bank  
35768      경기도  계약확정              0           없음     여자          NaN    NaN  
43022    광주광역시  계약확정              0           없음     여자          NaN    NaN  
49993    서울특별시  계약확정              0           없음     여자          NaN    NaN  
33803    인천광역시  계약확정              0           없음     여자          NaN    NaN  
45246    서울특별시  계약확정              0           없음     여자          NaN    NaN  
...        ...   ...            ...          ...    ...          ...    ...  
5399       경기도  계약확정              1           있음     여자          NaN   신한은행  
49896      경기도  계약확정              0           없음     여자          NaN    NaN  
49897      경기도  계약확정              0           없음     여자          NaN    NaN  
28147      경상도  계약확정              0           없음     여자          NaN   국민은행  
38497      전라도  계약확정              0           없음     남자          1.0  농협중앙회  

[51301 rows x 20 columns]

In [147]:
# 내림차순
# ascending = False
df1.sort_values(by='Amount_Month', ascending = False)

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
19773  19775   25740247         렌탈        프로모션계약    전단홍보  2022-11-13    39   
28147  28149   25704137         렌탈        프로모션계약    전단홍보  2022-07-24    39   
19413  19415   25710320         렌탈        프로모션계약    영업방판  2023-01-28    39   
19412  19414   25710321         렌탈        프로모션계약    영업방판  2022-09-14    39   
37522  37524   25733781         렌탈        프로모션계약    영업방판  2023-07-02    39   
...      ...        ...        ...           ...     ...         ...   ...   
45304  45306   66793756        멤버십        멤버십2유형   전문매장H  2022-10-06    36   
50428  50430   66797402        멤버십        멤버십2유형   전문매장H  2022-12-26    36   
45302  45304   66793342        멤버십        멤버십2유형   전문매장H  2022-04-02    36   
41153  41155   66790864        멤버십        멤버십2유형   전문매장H  2022-02-15    36   
39373  39375   66788207        멤버십        멤버십2유형   전문매장H  2023-05-11    36   

      Payment_Type Product_Type  Amount_Month Customer_Type  Age Address1  \
19773         가상계좌          MMC        215700           사업자  NaN      경상도   
28147          CMS          MMC        215700           사업자  NaN      경상도   
19413          CMS          MMC        215700           사업자  NaN      경기도   
19412          CMS          MMC        215700           사업자  NaN      경기도   
37522          CMS          MMC        215700           사업자  NaN      경기도   
...            ...          ...           ...           ...  ...      ...   
45304          무통장        DES-1         54603            개인  NaN      충청도   
50428          무통장        DES-1         54603            개인  NaN      경기도   
45302          무통장        DES-1         54603            개인  NaN      강원도   
41153          무통장        DES-1         54603            개인  NaN      경기도   
39373          무통장        DES-1         54603            개인  NaN      제주도   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank  Bank  
19773      경상도  계약확정              0           없음     여자          NaN   NaN  
28147      경상도  계약확정              0           없음     여자          NaN  국민은행  
19413      경기도  계약확정              0           없음     여자          NaN  기업은행  
19412      경기도  계약확정              0           없음     여자          NaN  기업은행  
37522      경기도  계약확정              0           없음     여자          NaN  기업은행  
...        ...   ...            ...          ...    ...          ...   ...  
45304      충청도  계약확정              0           없음     여자          NaN   NaN  
50428      경기도  계약확정              0           없음     여자          NaN   NaN  
45302      강원도  계약확정              0           없음     여자          NaN   NaN  
41153      경기도  계약확정              0           없음     여자          NaN   NaN  
39373      제주도  계약확정              0           없음     여자          NaN   NaN  

[51301 rows x 20 columns]

In [151]:
# 여러 컬럼을 정렬 할 때
# amount_month : 월 구매 금액 
#overdue_count : 연체횟수
# 월 구매금액이 높으면서 , 연체 횟수가 낮은 고객들을 출력
df2=df1.sort_values( by=['Amount_Month','Overdue_count'],
               ascending= [False , True])
df2[['Amount_Month','Overdue_count']]

Amount_Month  Overdue_count
19412        215700              0
19413        215700              0
19773        215700              0
19774        215700              0
28147        215700              0
...             ...            ...
51277         54603              0
51280         54603              0
51284         54603              0
51290         54603              0
42145         54603              1

[51301 rows x 2 columns]